 
SET search_path = administrative, pg_catalog;

--
-- TOC entry 4437 (class 0 OID 251512)
-- Dependencies: 219
-- Data for Name: condition_type; Type: TABLE DATA; Schema: administrative; Owner: postgres
--

INSERT INTO condition_type VALUES ('ktbs12-2rem', 'Any such exercise of the power to re-enter shall be without prejudice to any right of action or remedy of the Governor for any antecedent breach of  covenant by the rightholder(s).::::::::::::::::::::::::', 'Case for re-entry is without prejudice::::::::::::::::::::::::', 'c', 'cofo', NULL, NULL);
INSERT INTO condition_type VALUES ('ktag3', 'To pay such compensation as may be fixed by the Governor or any other person  authorised by him for disturbance of native occupation and for such timber, rubber and oil palm trees or other economic products as may be growing on the said land at the date of this certificate::::::::::::::::::::::::', 'To pay compensation::::::::::::::::::::::::', 'c', 'cofo', NULL, NULL);
INSERT INTO condition_type VALUES ('ktag4', 'To bring the farmable portion of the said land progressively under cultivation pasture or other agricultural use to the satisfaction of the Permanent Secretary, Ministry of Agriculture or other officer authorised by him at an annual rate of not less than one-eighth of the said portion until the whole of the said land portion is in cultivation pasture or use ::::::::::::::::::::::::', 'To bring under agricultural use::::::::::::::::::::::::', 'c', 'cofo', NULL, NULL);
INSERT INTO condition_type VALUES ('ktag4rem', 'Thereafter to keep the whole of the said portion in cultivation pasture or agricultural use to the satisfaction of the Permanent Secretary, Ministry of Agriculture or other officer authorised by him::::::::::::::::::::::::', 'To keep land under agricultural use::::::::::::::::::::::::', 'c', 'cofo', NULL, NULL);
INSERT INTO condition_type VALUES ('ktag5', 'To take such steps as the Divisional Engineer may from time to time require for the purpose of protecting the said land from damage by erosion and to refrain from any action ::::::::::::::::::::::::', '', 'c', 'cofo', NULL, NULL);
INSERT INTO condition_type VALUES ('ktag6', 'To enclose and fence securely any part of the said land as may be used for the herding, rearing, stalling or grazing of livestock in order safely to contain them at all times therein and for this purpose to erect and maintain such enclosing fences, walls or palisades and take such other measures as may be required by the Divisional Engineer::::::::::::::::::::::::', 'To enclose and fence securely::::::::::::::::::::::::', 'c', 'cofo', NULL, NULL);
INSERT INTO condition_type VALUES ('ktag7', 'On demand to pay such compensation as may be assessed by the Divisional Engineer or by an Local Authority acting on behalf, on account of any damage or injury done to persons, animals, buildings, trees or crops that shall be caused by any omission to keep livestock confined in the manner provided by other clauses in this certificate of occupancy.::::::::::::::::::::::::', 'Compensation for damage caused by omissions in fencing::::::::::::::::::::::::', 'c', 'cofo', NULL, NULL);
INSERT INTO condition_type VALUES ('ktag7rem', 'Such demands are subject to a right of appeal to the Commissioner whose decision shall be final against any award of compensation made by the Divisional Engineer or Local Authority in respect of such damage or injury::::::::::::::::::::::::', 'Right of appeal for demands for compensation::::::::::::::::::::::::', 'c', 'cofo', NULL, NULL);
INSERT INTO condition_type VALUES ('ktag8', 'Should livestock be brought on the said land to take such measures as the Divisional Engineer may direct to prevent over stocking or other damage to the said land by the said livestock::::::::::::::::::::::::', 'Not to over stock::::::::::::::::::::::::', 'c', 'cofo', NULL, NULL);
INSERT INTO condition_type VALUES ('ktag9a', 'Not to construct upon the said land any dwelling, houses or any permanent erections except for labourers''  huts and buildings designed for storing  agricultural machinery, tools or produce of for other purposes directly connected with the carrying on of cultivation, planting or farming or the housing of livestock except as specifically allowed for in other clauses in this certificate::::::::::::::::::::::::', 'Not to erect permanent buildings except for what is specifically allowed ::::::::::::::::::::::::', 'c', 'cofo', NULL, NULL);
INSERT INTO condition_type VALUES ('ktag9b1', 'To erect buildings and or other works to the satisfaction of the Governor (or other officer appointed by him) and within the specified period  from the commencement of this right of occupancy. The specified period is -::::::::::::::::::::::::', 'To erect any buildings within a specified time::::::::::::::::::::::::', 'c', 'cofo', NULL, NULL);
INSERT INTO condition_type VALUES ('ktag10', 'Unless authorised in writing thereto by the Divisional Engineer, not to plant any trees, shrubs or crops and not to erect any building within one hundred  feet of the centre line of any main road::::::::::::::::::::::::', 'Not to plant trees or erect buildings within 100 feet of any main road::::::::::::::::::::::::', 'c', 'cofo', NULL, NULL);
INSERT INTO condition_type VALUES ('ktag11', 'Not without the written consent of the Governor or any other person authorised by him, to pollute, dam or divert or in any way interfere directly or indirectly with any stream, pond, river or lake::::::::::::::::::::::::', 'Not to pollute, dam or divert or interfere with any water course or body::::::::::::::::::::::::', 'c', 'cofo', NULL, NULL);
INSERT INTO condition_type VALUES ('ktag12', 'To take such measures as the Divisional Engineer may require to prevent the contamination of any water supply arising by reason of the occupation by the right holder(s) of the said land or of any operation thereon by the said right holder(s) whether such supply be for human or animal consumption or for the irrigation of any land::::::::::::::::::::::::', 'To take measures to prevent contamination of water supplies::::::::::::::::::::::::', 'c', 'cofo', NULL, NULL);
INSERT INTO condition_type VALUES ('ktag13', 'Upon the expiration of the said term to render up to the Minister in good and substantial repair to the satisfaction of the Minister (or officer appointed by him/her), all buildings on the said land erected in pursuance hereof which have not been removed with the consent of the Governor and all buildings already upon the said land at the commencement of the said term which have not been removed::::::::::::::::::::::::', 'To render up buildings in good and substantial repair at the expiration of the term::::::::::::::::::::::::', 'c', 'cofo', NULL, NULL);
INSERT INTO condition_type VALUES ('ktag14', 'To clear and keep clear the said land of stagnant water, long grass, rank weeds, bush, accumulations and deposits of rubbish and other unwholesome matter and generally to keep the same and all buildings erected in a clean and sanitary condition to the satisfaction of the Health Officer and for such purposes to and execute all such acts and works as the Health Officer or any other officer authorised by him may reasonably require::::::::::::::::::::::::', 'To keep the land and buildings in clean and sanitary condition::::::::::::::::::::::::', 'c', 'cofo', NULL, NULL);
INSERT INTO condition_type VALUES ('ktbs12-2case1', 'If the yearly rent for the time being payable in respect of the said land or any part thereof shall be in arrears for the space of three months, whether the same or shall not have been legally demanded.::::::::::::::::::::::::', 'Case for re-entry for rent arrears (also ktag2-2case1)::::::::::::::::::::::::', 'c', 'cofo', NULL, NULL);
INSERT INTO condition_type VALUES ('ktbs12-2case2', ' If the rightholder(s) become bankrupt or make a composition with creditors or enter into liquidation, whether compulsory or voluntary.::::::::::::::::::::::::', 'Case for re-entry if bankrupt or in liquidation (also ktag2-2case2)::::::::::::::::::::::::', 'c', 'cofo', NULL, NULL);
INSERT INTO condition_type VALUES ('ktbs12-2case3', 'If there shall be any breach or non-observance of any of the occupier’s covenants or agreements herein contained.::::::::::::::::::::::::', 'Case for re-entry - non-compliance with conditions and agreements (also ktag2-2case3)::::::::::::::::::::::::', 'c', 'cofo', NULL, NULL);
INSERT INTO condition_type VALUES ('ktbs2', 'To pay and discharge all rates, taxes, assessments and impositions whatsoever which shall at any time be charged, assessed or imposed on the said land or any part thereof or any building thereon, or upon the occupier or occupiers thereof::::::::::::::::::::::::', 'To pay other charges (also ktag2)::::::::::::::::::::::::', 'c', 'cofo', NULL, NULL);
INSERT INTO condition_type VALUES ('ktbs3', 'To pay forthwith without demand to the Governor or other person appointed by him on the issue of this certificate (if not sooner paid) all survey fees, registration fees and other charges due in respect of the preparation and issue and registration of this certificate::::::::::::::::::::::::', 'To pay for the preparation of this certification including registration and survey fees::::::::::::::::::::::::', 'c', 'cofo', NULL, NULL);
INSERT INTO condition_type VALUES ('ktbs4', 'To erect and complete on the said land the buildings and other works specified in detailed plans approved or to be approved by the officer appointed by the Governor. These buildings and other works to be erected and completed in accordance with the approved plans to the satisfaction of the officer appointed by the Governor. From the date of the commencement of this right of occupancy, such work to be completed within -  ::::::::::::::::::::::::', 'To complete proposed buildings and other works within specified time::::::::::::::::::::::::', 'c', 'cofo', NULL, NULL);
INSERT INTO condition_type VALUES ('ktbs4b', 'The value of the buildings and other works shall be not less than -::::::::::::::::::::::::', 'Value of buildings and other works::::::::::::::::::::::::', 'c', 'cofo', NULL, NULL);
INSERT INTO condition_type VALUES ('ktbs5', 'To maintain in good substantial repair to the satisfaction of the said or other officer appointed by the Governor, all buildings on the said land (whether now erected or to be erected in pursuance of other stated conditions::::::::::::::::::::::::', 'To maintain buildings in good repair::::::::::::::::::::::::', 'c', 'cofo', NULL, NULL);
INSERT INTO condition_type VALUES ('ktbs6', 'To clear and keep clear the said land of stagnant water, long grass, rank weeds and bush and accumulations and deposits of rubbish and other unwholesome matter, and to keep the same in all respects in a clean and sanitary condition, and for such purposed to do and execute all such acts and works as the Governor or any officer authorised  by him may reasonably require::::::::::::::::::::::::', 'To keep tidy::::::::::::::::::::::::', 'c', 'cofo', NULL, NULL);
INSERT INTO condition_type VALUES ('ktbs7', 'To conform to all rules laid down from time to time in regard to the location of buildings, refuse pits and latrines::::::::::::::::::::::::', 'Location of buildings::::::::::::::::::::::::', 'c', 'cofo', NULL, NULL);
INSERT INTO condition_type VALUES ('ktbs8', 'The land shall not be unoccupied for any period exceeding six months at any one time, or eight months in any year from the specified period of time after the commencement of this right of occupancy. This specified period of time following the commencement of this right of occupancy is -::::::::::::::::::::::::', 'Not to leave the land unoccupied::::::::::::::::::::::::', 'c', 'cofo', NULL, NULL);
INSERT INTO condition_type VALUES ('ktbs9', 'Upon the expiration of the term of this right of occupancy, to render up to the Governor in good and substantial repair to the satisfaction of the officers appointed by the Governor all buildings on the said land erected in pursuance hereof which have not been removed with the consent of the Governor and all buildings already upon the said land at the commencement of the said term of the right of occupancy which have not been removed. ::::::::::::::::::::::::', 'To render up the land and buildings at the end of the term of the right of occupancy::::::::::::::::::::::::', 'c', 'cofo', NULL, NULL);
INSERT INTO condition_type VALUES ('ktbs10', 'Not to erect or build or permit to be erected or built on the said land any buildings other than those covenanted to be erected by virtue to this certificate of occupancy nor to make or permit to be made any addition or alteration to the said buildings to be erected or buildings already erected on the land except in accordance with plans and specifications approved by the said or other officer appointed by the Governor on his behalf::::::::::::::::::::::::', 'Not to erect or build any other buildings::::::::::::::::::::::::', 'c', 'cofo', NULL, NULL);
INSERT INTO condition_type VALUES ('ktbs11', 'Not to alienate the right of occupancy hereby granted or any part thereof by sale, assignment, mortgage, transfer or possession, sub-lease or bequest or otherwise however without the consent of the Governor first had and obtained::::::::::::::::::::::::', 'Not to alienate with the consent of the Governor::::::::::::::::::::::::', 'c', 'cofo', NULL, NULL);
INSERT INTO condition_type VALUES ('ktbs12', 'To use the said land only for the purpose of::::::::::::::::::::::::', 'Only to use the land for the stated purpose(s)::::::::::::::::::::::::', 'c', 'cofo', NULL, NULL);
INSERT INTO condition_type VALUES ('ktbs1', 'To pay in advance without demand to the Governor, or other person appointed by him, the stated proportion of the rent applicable in the first year of this right of occupancy and then the stated annual rent payable on the first day of January each year::::::::::::::::::::::::', 'To pay rent (also ktag1)::::::::::::::::::::::::', 'c', 'cofo', NULL, NULL);
INSERT INTO condition_type VALUES ('ktbbs12-1rem4', 'This additional rent owing is for the period between  the unrevised rent and the revised rent for the period (if any) between the date of revision and the thirty-first day of December in the year then current::::::::::::::::::::::::', 'Period for additional rent payment following rent review::::::::::::::::::::::::', 'c', 'cofo', NULL, NULL);
INSERT INTO condition_type VALUES ('ktbs12-1rem1', 'The Governor may as near as it is convenient to the expiration of a rent review period, revise the rent and fix a revised rent which shall apply for the next rent review period or if the term of the right of occupancy falls within the next rent review period, the remainder of the term.::::::::::::::::::::::::', 'Revise the rent (also ktag2-1rem1)::::::::::::::::::::::::', 'c', 'cofo', NULL, NULL);
INSERT INTO condition_type VALUES ('ktbs12-1rem2', 'If the Governor does revise the rent, he shall cause a notice in writing to be sent to the right holder(s) informing them of the revision of the rent. ::::::::::::::::::::::::', 'Notice of rent review (also ktag2-1rem2)::::::::::::::::::::::::', 'c', 'cofo', NULL, NULL);
INSERT INTO condition_type VALUES ('ktag15', 'Not to alienate the right of occupancy hereby granted or any part thereof by sale, mortgage, transfer of possession, sub-lease or bequest or otherwise howsoever without the consent of the Governor first had and obtained::::::::::::::::::::::::', 'Not to alienate the right of occupancy::::::::::::::::::::::::', 'c', 'cofo', NULL, NULL);
INSERT INTO condition_type VALUES ('ktag16', 'To use the said land only for the purpose of -::::::::::::::::::::::::', 'To only use the land for the specified purpose::::::::::::::::::::::::', 'c', 'cofo', NULL, NULL);
INSERT INTO condition_type VALUES ('ktag17', 'In the event of carrying on the business of animal rearing or slaughtering or the dressing, preparation or any products thereon, to carry on the same in a husband like and hygienic manner to the satisfaction of the Permanent Secretary, Ministry of Animal and Forest Resources and the Health Officer or any officer appointed by them.::::::::::::::::::::::::', 'To carry out animal rearing or slaughtering in a husband like and hygienic manner::::::::::::::::::::::::', 'c', 'cofo', NULL, NULL);
INSERT INTO condition_type VALUES ('ktag17rem1', 'o erect all buildings, structures or other fixtures in connection with animal rearing or slaughtering ( as identified in the previous clause) therewith according to plans and specifications that shall be approved and subject to any conditions that may be imposed by the Health Officer ::::::::::::::::::::::::', 'Any buildings or structures to be built in accordance with approved plans and specifications::::::::::::::::::::::::', 'c', 'cofo', NULL, NULL);
INSERT INTO condition_type VALUES ('ktag17rem2', 'To take such measures as the Health Officer may prescribe for the disposal of effluents and waste products and for the prevention of the contamination of any water supply. Whether such supply be for human or animal consumption or for the irrigation or cultivation of any land::::::::::::::::::::::::', 'To take adequate measure for the disposal of effluents and waste products::::::::::::::::::::::::', 'c', 'cofo', NULL, NULL);
INSERT INTO condition_type VALUES ('ktbs12-1', 'For the purpose of the rent to be paid under this certificate of occupancy, the term of the right of occupancy shall be divided into standard rent review periods. The rent review period for this certificate of occupancy shall be –::::::::::::::::::::::::', 'Authority to revise the rent paid (also ktag2-1)::::::::::::::::::::::::', 'c', 'cofo', NULL, NULL);
INSERT INTO condition_type VALUES ('ktbs12-1rem3', 'The right holder(s) shall thereupon within one month of the date of the receipt of such a notice, or within seven days of the commencement of the period for which the rent has been revised, whichever shall last happen, without further demand, pay to the Governor or to other persons appointed by him the additional rent owing for the current year.::::::::::::::::::::::::', 'Additional Rent to be paid for year in which rent is revised (also ktag2-1rem3)::::::::::::::::::::::::', 'c', 'cofo', NULL, NULL);
INSERT INTO condition_type VALUES ('ktbs12-1rem4', 'Thereafter the rightholders shall pay in advance on the first day of January in each year without demand to the Governor or other persons appointed by him in lieu the latest revised rent.::::::::::::::::::::::::', 'Obligation to pay revised rent in advance (ktag2-1rem4)::::::::::::::::::::::::', 'c', 'cofo', NULL, NULL);
INSERT INTO condition_type VALUES ('ktbs12-2', 'It shall be lawful for the Governor at any time to re-enter upon the said land or any part thereof in the name of the whole and henceforth hold and enjoy the same as if the right of occupancy had not been granted should the following cases eventuate:::::::::::::::::::::::::', 'Right to re-enter land in certain cases (also ktag2-2)::::::::::::::::::::::::', 'c', 'cofo', NULL, NULL);
INSERT INTO condition_type VALUES ('ktag3plus', 'Persons in lawful occupation of any part of the said land at the time of the issue of the certificate shall always have an option either ::::::::::::::::::::::::', 'Persons in lawful occupation at commencement of certificate::::::::::::::::::::::::', 'c', 'cofo', NULL, NULL);
INSERT INTO condition_type VALUES ('ktag3plusOption1', 'To quit immediately the area subject to this right of occupancy and at once to receive from the right holder(s) the full value of improvements and compensation for disturbance::::::::::::::::::::::::', 'To quit immediately and receiver compensation::::::::::::::::::::::::', 'c', 'cofo', NULL, NULL);
INSERT INTO condition_type VALUES ('ktag3plusOption2', 'To remain in occupation of their buildings until the right holder(s) requires possession or they desire to quit, and receive the compensation assessed at the time of the issue of this certificate upon their relinquishing their holdings on demand by the right holder(s) or voluntarily, as the case may be::::::::::::::::::::::::', 'To remain in occupation for a period of time::::::::::::::::::::::::', 'c', 'cofo', NULL, NULL);





INSERT INTO system.version SELECT '1604c' WHERE NOT EXISTS (SELECT version_num FROM system.version WHERE version_num = '1604c');